all: main.cpp csv.cpp csv.h vec2.h string_utils.cpp string_utils.h

main.cpp: main.t; letangle.exe main.t > main.cpp
csv.cpp: csv.t; letangle.exe csv.t csv.cpp > csv.cpp
csv.h: csv.t; letangle.exe csv.t csv.h > csv.h
vec2.h: vec2.t; letangle.exe vec2.t > vec2.h
string_utils.cpp: string_utils.t; letangle.exe string_utils.t string_utils.cpp > string_utils.cpp
string_utils.h: string_utils.t; letangle.exe string_utils.t string_utils.h > string_utils.h
