all: main.cpp parser.cpp parser.h

main.cpp: main.t; letangle.exe main.t > main.cpp
parser.cpp: parser.t; letangle.exe parser.t parser.cpp > parser.cpp
parser.h: parser.t; letangle.exe parser.t parser.h > parser.h
