all: main.cpp Ofloat.h newton_test.cpp newton_test.h machin.h

main.cpp: main.t; letangle.exe main.t > main.cpp
Ofloat.h: Ofloat.t; letangle.exe Ofloat.t Ofloat.h > Ofloat.h
newton_test.h: newton_test.t; letangle.exe newton_test.t newton_test.h > newton_test.h
newton_test.cpp: newton_test.t; letangle.exe newton_test.t newton_test.cpp > newton_test.cpp
machin.h: machin.t; letangle.exe machin.t machin.h > machin.h
